### PR TITLE
convert between urdf/smurf and rock/envire transformation convention …

### PR DESCRIPTION
**Pull request by maltewi**
…when importing static transforms from URDF

### CODE REVIEW

**Comment by Rauldg** [comment]
This PR aims for inverting the way transformations are represented when loading an URDF or SMURF robot model. Correct?

There are comments about `envire/rock` [here](https://github.com/envire/envire-envire_smurf/pull/6/files#diff-eef7853eb80f716e8933591b52af8021R351). Envire is not rock dependent. The way the transformations are represented in Envire is not to be changed without a reason for that other than `doing it the Rock way`.

**Comment by maltewi** [comment]
The question is: What is the convention is envire? There should be one. Is it he one from rock or the one from URDF?
I thought Envire uses the Rock convention.

**Comment by Rauldg** [comment]
Envire follows so far the opposite convention indeed. Which during the development meetings was found to be more widely accepted and intuitive for the majority of developers. But indeed there was discussion... 

Changing the convention would have impact in all envire-based applications, is not only about the robot loader.

**Comment by Rauldg** [comment]
One option would be to have an attribute on the robot-model class, so you can decide the convention to use when loading the robot, by default the convention should be envire-classical one to keep backwards compatibility.

What do you think? I think It can bring ease of use to the Rock developers but extra flexibility increases also complexity. 

For me the attribute to state the convention is an acceptable solution, but I don't know the impact that it would have in other applications. For instance, a robot loaded with the rock convention, would fail in envire-mars and I guess same goes for envire-based visualizations.

**Comment by maltewi** [comment]
Thanks @Rauldg, that's good to know. Is there a reference somewhere about the used convention? 

Regarding my issue: I'll just do the conversion then at a different place.. that's no problem.

@skasperski: I added you here because we've discussed in this regard. If you have something to add to the thread here, go ahead. Otherwise I'll close the issue the next days.

**Comment by skasperski** [comment]
I agree, there is no need to change Envire for our usecase. I'm fine with any convention, as long as I know which one it is. We have to switch in certain situations anyway, no matter what Envire does.

**Comment by saarnold** [comment]
If I remember correctly it was agreed that origin -> target in envire represents the transformation of the target frame expressed in the origin frame. 

In contrast, and probably the root of this discussion, the naming convention in the rock base type RigidBodyState is the source frame expressed in the target frame.

The core of this problem is that the names source and target are ambiguous when it comes to transformations and should therefore be avoided. (Side note: The stored transformations however are never to be inverted)

I agree with @maltewi that it lacks documentation in envire core.

**Comment by Rauldg** [comment]
> Is there a reference somewhere about the used convention?

I think it is not documented. At least, I was just looking through it and couldn't find it. One thing I found, that could help in your case is that the envire graph actually maintains each transformation in both directions [see the note about the double-link architecture](https://github.com/envire/envire-envire_core#structure).

> If I remember correctly it was agreed that origin -> target in envire represents the transformation of the target frame expressed in the origin frame.

I think so too.

**Comment by maltewi** [comment]
Closed because issue was opened caused by a wrong assumption about the frame naming convention in envire.

A documentation about the convention would be nice, but this is a different issue and does not belong here.

My issue will be solved a different place (not in any envire-related software part).

**Pull request closed without merging**
